---
- name: 'get Oracle Java RPM: {{ java_oracle_rpm }}'
  get_url:
    url: '{{ java_oracle_url }}'
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: '/tmp/{{ java_oracle_rpm }}'
  tags: java

- name: 'install Oracle Java RPM: {{ java_oracle_rpm }}'
  yum:
    name: '/tmp/{{ java_oracle_rpm }}'
    state: present
  tags: java
